name = "DistMesh"
uuid = "f7ee28b6-bfbf-11e9-3e31-8961b86f052c"
authors = ["Steve Kelly <kd2cca@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
